//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 04:38:55 PM CST 
//


package hk.org.ha.cid_login_ws.cidloginfunctions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefaultLoginInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefaultLoginInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initUsrId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initCmsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultLoginInfo", propOrder = {
    "initUserName",
    "initDomain",
    "initUsrId",
    "initCmsId"
})
public class DefaultLoginInfo {

    protected String initUserName;
    protected String initDomain;
    protected String initUsrId;
    protected String initCmsId;

    /**
     * Gets the value of the initUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitUserName() {
        return initUserName;
    }

    /**
     * Sets the value of the initUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitUserName(String value) {
        this.initUserName = value;
    }

    /**
     * Gets the value of the initDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitDomain() {
        return initDomain;
    }

    /**
     * Sets the value of the initDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitDomain(String value) {
        this.initDomain = value;
    }

    /**
     * Gets the value of the initUsrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitUsrId() {
        return initUsrId;
    }

    /**
     * Sets the value of the initUsrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitUsrId(String value) {
        this.initUsrId = value;
    }

    /**
     * Gets the value of the initCmsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitCmsId() {
        return initCmsId;
    }

    /**
     * Sets the value of the initCmsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitCmsId(String value) {
        this.initCmsId = value;
    }

}
