//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 04:38:55 PM CST 
//


package hk.org.ha.cid_login_ws.cidloginfunctions;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hk.org.ha.cid_login_ws.cidloginfunctions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hk.org.ha.cid_login_ws.cidloginfunctions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeDomainPasswordResponse }
     * 
     */
    public ChangeDomainPasswordResponse createChangeDomainPasswordResponse() {
        return new ChangeDomainPasswordResponse();
    }

    /**
     * Create an instance of {@link AdminChangeDomainPassword }
     * 
     */
    public AdminChangeDomainPassword createAdminChangeDomainPassword() {
        return new AdminChangeDomainPassword();
    }

    /**
     * Create an instance of {@link GetChangeDomainPasswordReturnMessage }
     * 
     */
    public GetChangeDomainPasswordReturnMessage createGetChangeDomainPasswordReturnMessage() {
        return new GetChangeDomainPasswordReturnMessage();
    }

    /**
     * Create an instance of {@link LoginInfo }
     * 
     */
    public LoginInfo createLoginInfo() {
        return new LoginInfo();
    }

    /**
     * Create an instance of {@link SqlLoginResponse }
     * 
     */
    public SqlLoginResponse createSqlLoginResponse() {
        return new SqlLoginResponse();
    }

    /**
     * Create an instance of {@link SqlLoginChangePassword }
     * 
     */
    public SqlLoginChangePassword createSqlLoginChangePassword() {
        return new SqlLoginChangePassword();
    }

    /**
     * Create an instance of {@link GetChangeDomainPasswordReturnMessageResponse }
     * 
     */
    public GetChangeDomainPasswordReturnMessageResponse createGetChangeDomainPasswordReturnMessageResponse() {
        return new GetChangeDomainPasswordReturnMessageResponse();
    }

    /**
     * Create an instance of {@link CheckLoginResponse }
     * 
     */
    public CheckLoginResponse createCheckLoginResponse() {
        return new CheckLoginResponse();
    }

    /**
     * Create an instance of {@link AdminChangeDomainPasswordResponse }
     * 
     */
    public AdminChangeDomainPasswordResponse createAdminChangeDomainPasswordResponse() {
        return new AdminChangeDomainPasswordResponse();
    }

    /**
     * Create an instance of {@link ShowNewsIframeResponse }
     * 
     */
    public ShowNewsIframeResponse createShowNewsIframeResponse() {
        return new ShowNewsIframeResponse();
    }

    /**
     * Create an instance of {@link GetDefaultLoginResponse }
     * 
     */
    public GetDefaultLoginResponse createGetDefaultLoginResponse() {
        return new GetDefaultLoginResponse();
    }

    /**
     * Create an instance of {@link ShowNewsIframe }
     * 
     */
    public ShowNewsIframe createShowNewsIframe() {
        return new ShowNewsIframe();
    }

    /**
     * Create an instance of {@link CheckLoginMethodResponse }
     * 
     */
    public CheckLoginMethodResponse createCheckLoginMethodResponse() {
        return new CheckLoginMethodResponse();
    }

    /**
     * Create an instance of {@link SqlLogin }
     * 
     */
    public SqlLogin createSqlLogin() {
        return new SqlLogin();
    }

    /**
     * Create an instance of {@link GetCidReturnMessageResponse }
     * 
     */
    public GetCidReturnMessageResponse createGetCidReturnMessageResponse() {
        return new GetCidReturnMessageResponse();
    }

    /**
     * Create an instance of {@link DefaultLoginInfo }
     * 
     */
    public DefaultLoginInfo createDefaultLoginInfo() {
        return new DefaultLoginInfo();
    }

    /**
     * Create an instance of {@link CheckLoginMethod }
     * 
     */
    public CheckLoginMethod createCheckLoginMethod() {
        return new CheckLoginMethod();
    }

    /**
     * Create an instance of {@link ChangeDomainPassword }
     * 
     */
    public ChangeDomainPassword createChangeDomainPassword() {
        return new ChangeDomainPassword();
    }

    /**
     * Create an instance of {@link CheckLogin }
     * 
     */
    public CheckLogin createCheckLogin() {
        return new CheckLogin();
    }

    /**
     * Create an instance of {@link SqlLoginChangePasswordResponse }
     * 
     */
    public SqlLoginChangePasswordResponse createSqlLoginChangePasswordResponse() {
        return new SqlLoginChangePasswordResponse();
    }

    /**
     * Create an instance of {@link GetDefaultLogin }
     * 
     */
    public GetDefaultLogin createGetDefaultLogin() {
        return new GetDefaultLogin();
    }

    /**
     * Create an instance of {@link GetCidReturnMessage }
     * 
     */
    public GetCidReturnMessage createGetCidReturnMessage() {
        return new GetCidReturnMessage();
    }

}
