  CREATE TABLE "V_JOB_RANK" 
   (	"JOB_RANK_CODE" VARCHAR2(20 BYTE), 
	"JOB_RANK_NAME" VARCHAR2(50 BYTE), 
	"STAFF_GROUP" VARCHAR2(20 BYTE)
   );
   
Insert into V_JOB_RANK (JOB_RANK_CODE,JOB_RANK_NAME,STAFF_GROUP) values ('AC','AC','ME');
Insert into V_JOB_RANK (JOB_RANK_CODE,JOB_RANK_NAME,STAFF_GROUP) values ('EN','EN','NU');
Insert into V_JOB_RANK (JOB_RANK_CODE,JOB_RANK_NAME,STAFF_GROUP) values ('RN','RN','NU');
