CREATE TABLE ."V_STAFF_GROUP" 
   (	"STAFF_GRP_CODE" VARCHAR2(5 BYTE), 
		"STAFF_GRP_NAME" VARCHAR2(20 BYTE)
   );
   
Insert into V_STAFF_GROUP (STAFF_GRP_CODE,STAFF_GRP_NAME) values ('NU','Nursing');
Insert into V_STAFF_GROUP (STAFF_GRP_CODE,STAFF_GRP_NAME) values ('ME','Medical');