CREATE TABLE XXEAL_PAYMENT_JOB (
	BATCH_JOB_ID integer NOT NULL,
  	BATCH_ID integer  NOT NULL,
	RANK VARCHAR2(20 BYTE) NOT NULL,
	REC_STATE VARCHAR2(1 BYTE),
	CREATED_BY VARCHAR2(20 BYTE),
	CREATED_ROLE_ID VARCHAR2(20 BYTE),
	CREATED_DATE TIMESTAMP (6),
	UPDATED_BY VARCHAR2(20 BYTE),
	UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  	UPDATED_DATE TIMESTAMP (6)
) ;


  ALTER TABLE "XXEAL_PAYMENT_JOB" ADD CONSTRAINT "XXEAL_PAYMENT_JOB_PK" PRIMARY KEY ("BATCH_JOB_ID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
