CREATE TABLE XXEAL_PAYMENT_BATCH (
    BATCH_ID integer  NOT NULL,
    PAYMENT_TYPE varchar2(10)  NOT NULL,
    PROJECT_ID integer  NOT NULL,
    DEPARTMENT_ID integer  NOT NULL,
    LOCATION_ID integer ,
    PAY_MONTH date  NOT NULL,
    LAST_UPDATE_DATE date  ,
    STATUS varchar2(10)  NOT NULL,
    TOTAL_TXN integer  ,
    NO_OF_APPROVED_TXN integer  ,
    NO_OF_ON_HOLD_TXN integer  ,
    NO_OF_HA_CS_PAYROLL_TXN integer  ,
    NO_OF_REVIEWED_TXN integer  ,
    NO_OF_PENDING_TRANSFER_TXN integer  ,
    TRANSFERRED integer ,
    PARENT_BATCH_ID integer ,
    REASON varchar2(100) ,
	REC_STATE VARCHAR2(1 BYTE),
	CREATED_BY VARCHAR2(20 BYTE),
	CREATED_ROLE_ID VARCHAR2(20 BYTE),
	CREATED_DATE TIMESTAMP (6),
	UPDATED_BY VARCHAR2(20 BYTE),
	UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  	UPDATED_DATE TIMESTAMP (6)
) ;


  ALTER TABLE "XXEAL_PAYMENT_BATCH" ADD CONSTRAINT "XXEAL_PAYMENT_BATCH_PK" PRIMARY KEY ("BATCH_ID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
