CREATE TABLE XXEC_SHS_PROJECT_STATUS_M (
  PROJECT_STATUS_CODE VARCHAR2(5) NOT NULL,
  PROJECT_STATUS VARCHAR2(80),
  PROJECT_SEQUENCE NUMBER
);

ALTER TABLE "XXEC_SHS_PROJECT_STATUS_M" ADD CONSTRAINT "XXEC_SHS_PROJECT_STATUS_M_PK" PRIMARY KEY ("PROJECT_STATUS_CODE") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
