create table XXEC_PRJ_JOB_DETAIL (
  PRJ_JOB_DETAIL_ID NUMBER(10) NOT NULL,
  JOB_GROUP_ID NUMBER(10) NOT NULL,
  RANK VARCHAR2(10)
);

ALTER TABLE "XXEC_PRJ_JOB_DETAIL" ADD CONSTRAINT "XXEC_PRJ_JOB_DETAIL_PK" PRIMARY KEY ("PRJ_JOB_DETAIL_ID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
