  CREATE TABLE "ECLAIM"."XXEC_EMAIL_TEMPLATE" 
   (	"TEMPLATE_ID" VARCHAR2(20) NOT NULL, 
	"TEMPLATE_TITLE" VARCHAR2(500) NOT NULL, 
	"TEMPLATE_CONTENT" VARCHAR2(2000) NOT NULL, 
	"REC_STATE" VARCHAR2(1) NOT NULL, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ROLE_ID" VARCHAR2(20), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ROLE_ID" VARCHAR2(20), 
	"UPDATED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
    CREATE UNIQUE INDEX "ECLAIM"."CS_EMAIL_TEMPLATE_PK" ON "ECLAIM"."XXEC_EMAIL_TEMPLATE" ("TEMPLATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "ECLAIM"."XXEC_EMAIL_TEMPLATE" ADD CONSTRAINT "CS_EMAIL_TEMPLATE_PK" PRIMARY KEY ("TEMPLATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;