CREATE TABLE XXEC_SHS_PROJECT_CIRCUM (
    PROJECT_CIRCUM_UID NUMBER(10) NOT NULL,
    PROJECT_ID NUMBER(10) NOT NULL,
    PROJECT_VER_ID NUMBER(10) NOT NULL,
    CIRCUMSTANCE_ID NUMBER,
    Q_DELIVERABLES VARCHAR2(4000),
    REC_STATE VARCHAR2(1 BYTE),
    CREATED_BY VARCHAR2(20 BYTE),
	  CREATED_ROLE_ID VARCHAR2(20 BYTE),
	  CREATED_DATE TIMESTAMP (6),
	  UPDATED_BY VARCHAR2(20 BYTE),
	  UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  	UPDATED_DATE TIMESTAMP (6)
);
