CREATE TABLE XXEC_DOCUMENT (
    DOCUMENT_ID NUMBER(10) NOT NULL,
    PROJECT_ID NUMBER(10) NOT NULL,
    PROJECT_VER_ID NUMBER(10) NOT NULL,
    DESCRIPTIONQ VARCHAR2(4000),
    FILENAME VARCHAR2(150),
    PATH VARCHAR2(200),
    CATEGROY VARCHAR2(50),
    REC_STATE VARCHAR2(1 BYTE),
    CREATED_BY VARCHAR2(20 BYTE),
	  CREATED_ROLE_ID VARCHAR2(20 BYTE),
	  CREATED_DATE TIMESTAMP (6),
	  UPDATED_BY VARCHAR2(20 BYTE),
	  UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  	UPDATED_DATE TIMESTAMP (6)
  );

  ALTER TABLE "XXEC_DOCUMENT" ADD CONSTRAINT "XXEC_DOCUMENT_PK" PRIMARY KEY ("DOCUMENT_ID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
