  CREATE TABLE "ECLAIM"."XXEC_WORKFLOW_ROUTE" 
   (	"WF_ROUTE_UID" NUMBER(10,0) NOT NULL, 
	"STAFF_GROUP_CODE" VARCHAR2(20) NOT NULL, 
	"REQUEST_TYPE" VARCHAR2(20) NOT NULL, 
	"FROM_ROLE" VARCHAR2(20) NOT NULL, 
	"CURRENT_STATUS" VARCHAR2(20),
	"MG_REVIEW_IND" VARCHAR2(1),  
	"ACTION_NAME" VARCHAR2(20), 
	"ACTION_TAKEN" VARCHAR2(20), 
	"RETURN_TO_ROLE" VARCHAR2(200), 
	"SUBMIT_TO_ROLE" VARCHAR2(200), 
	"TARGET_STATUS" VARCHAR2(20), 
	"REC_STATE" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_ROLE_ID" VARCHAR2(20), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_ROLE_ID" VARCHAR2(20), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"RETURN_STATUS" VARCHAR2(20), 
	"TEMPLATE_ID" VARCHAR2(20), 
	"RETURN_TEMPLATE_ID" VARCHAR2(20), 
	"SUBMIT_CC_ROLE" VARCHAR2(200), 
	"RETURN_CC_ROLE" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;  
  
CREATE UNIQUE INDEX "ECLAIM"."RQ_WORKFLOW_ROUTE_PK" ON "ECLAIM"."XXEC_WORKFLOW_ROUTE" ("WF_ROUTE_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  ALTER TABLE "ECLAIM"."XXEC_WORKFLOW_ROUTE" ADD CONSTRAINT "RQ_WORKFLOW_ROUTE_PK" PRIMARY KEY ("WF_ROUTE_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;