CREATE TABLE XXEC_PROJECT_JOB (
  PROJECT_ID NUMBER(10) NOT NULL,
  PROJECT_VER_ID NUMBER(10) NOT NULL,
  JOB_GROUP_ID NUMBER(10) NOT NULL,
  STAFF_GROUP VARCHAR2(80),
  PROJECT_COORDINATOR_ID varchar2(20),
  PROJECT_COORDINATOR VARCHAR2(50),
  JOB_DESCRIPTION VARCHAR2(4000),
  QUOTA NUMBER(8,2),
  DURATION NUMBER(8,2),
  SESSION_PER_DAY NUMBER(8,2),
  HOURS_PER_SESSION NUMBER(8,2),
  TOTAL_HOUR NUMBER(8,2),
  OTHER_INFORMATION VARCHAR2(4000),
  TARGER_APPLICANT VARCHAR2(2000),
  REC_STATE VARCHAR2(1 BYTE),
  CREATED_BY VARCHAR2(20 BYTE),
  CREATED_ROLE_ID VARCHAR2(20 BYTE),
  CREATED_DATE TIMESTAMP (6),
  UPDATED_BY VARCHAR2(20 BYTE),
  UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  UPDATED_DATE TIMESTAMP (6)
);

ALTER TABLE "XXEC_PROJECT_JOB" ADD CONSTRAINT "XXEC_PROJECT_JOB_PK" PRIMARY KEY ("JOB_GROUP_ID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
