CREATE TABLE XXEC_APPROVAL_HISTORY(
  PROJECT_ID NUMBER(10) NOT NULL,
  PROJECT_VER_ID NUMBER(10) NOT NULL,
  APPR_HIST_UID NUMBER(10) NOT NULL,
  ACTION_BY VARCHAR2(50),
  ROLE_CODE VARCHAR2(20),
  ACTION_CODE VARCHAR2(10),
  ACTION_DATE TIMESTAMP (6),
  REMARK VARCHAR2(4000),
  REC_STATE VARCHAR2(1 BYTE),
  CREATED_BY VARCHAR2(20 BYTE),
  CREATED_ROLE_ID VARCHAR2(20 BYTE),
  CREATED_DATE TIMESTAMP (6),
  UPDATED_BY VARCHAR2(20 BYTE),
  UPDATED_ROLE_ID VARCHAR2(20 BYTE),
  UPDATED_DATE TIMESTAMP (6)
);

ALTER TABLE "XXEC_APPROVAL_HISTORY" ADD CONSTRAINT "XXEC_APPROVAL_HISTORY_PK" PRIMARY KEY ("APPR_HISTY_UID") USING INDEX TABLESPACE "XXHA_TS_TX_IDX" ENABLE;
