REM INSERTING into ECLAIM.XXEC_EMAIL_TEMPLATE
SET DEFINE OFF;
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RQ_CHG_STF_CONFIRM','MPRS - New Request of Change of Staff Mix has been confirmed (<para1>)','Dear <para9>
<br>
<br>
Please find the details of the confirmed Change of Staff Mix Request:
<br>
Request No:         <para1><br>
From Post ID:       <para2>
<br>
To Post ID:            <para5><br>
<br>
Confirmed By:        <para3>
<br>
Confirmation Date:  <para4><br>
<br>
<Supplementary Information / Comment>
<br>
<br>
Please click here to review the request
<br>
<br>
Regards,
<br>
MPRS - Manpower Position Registry System
<br>
<br>
(This e-mail is generated by MPRS automatically.  Please DO NOT REPLY to this email)','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RQ_NEW_POST_CONFIRM','MPRS - New Post Request has been confirmed (<para1>)','Dear
<para9>
<br>
<br>
Please find the details of the confirmed Post:
<br>
Request No:         <para1><br>
Confirmed Post ID: <para2><br>
<br>
Confirmed By:        <para3>
<br>
Confirmation Date:  <para4><br>
<br>
<Supplementary Information / Comment>
<br>
<br>
Please click here to review the request
<br>
<br>
Regards,
<br>
MPRS - Manpower Position Registry System
<br>
<br>
(This e-mail is generated by MPRS automatically.  Please DO NOT REPLY to this email)','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('NEW_PROJ_SUBMIT','New Project Initial is submitted (<para1>)','Dear <para9>
<br>
<br>
Please find the details of the confirmed Supplementary Promotion Request:
<br>
Request No:         <para1><br>
Post ID:                <para2><br>
<br>
Confirmed By:        <para3>
<br>
Confirmation Date:  <para4><br>
<br>
<Supplementary Information / Comment>
<br>
<br>
Please click here to review the request
<br>
<br>
Regards,
<br>
EClaim Administrator
<br>
<br>
(This e-mail is generated by MPRS automatically.  Please DO NOT REPLY to this email)','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('TO_PROJECT_OWNER','New SHS Project Initiation (<para1>) is drafted please review.','Dear Project Owner,
<br>
<br>
This is a new project initiation "<para1>" is drafted by <para7>. <br>Please review it by click this link.
<br>
<br>
Regards,
<br>
eClaim system administrator','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('TO_HR_OFFICER','New SHS Project Initiation (<para1>) is submitted please review.','Dear HRofficer,
<br>
<br>
This is a new project initiation "<para1>" is submitted by <para8>. <br>Please review it by click this link.
<br>
<br>
Regards,
<br>
eClaim system administrator','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('TO_FIN_ADMIN','New SHS Project Initiation (<para1>) is submitted please review.','Dear Fin Admin,
<br>
<br>
This is a new project initiation "<para1>" is submitted by <para8> and vetted by HR. <br>Please review it by click this link.
<br>
<br>
Regards,
<br>
eClaim system administrator','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('TO_FIN_HOSP_IC','New SHS Project Initiation (<para1>) is submitted please review.','Dear FIN hospital I/C,
<br>
<br>
This is a new project initiation "<para1>" is submitted by <para8> and vetted by HR and <para9>. <br>Please review it by click this link.
<br>
<br>
Regards,
<br>
eClaim system administrator','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('TO_HR_MANAGER','New SHS Project Initiation (<para1>) is submitted please review.','Dear HR Manager,
<br>
<br>
This is a new project initiation "<para1>" is submitted by <para8> and was vetted by HR and FIN. <br>Please review and approve it by click this link.
<br>
<br>
Regards,
<br>
eClaim system administrator','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RET_PREPARER','Title for return to preparer','Content for return to preparer','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RET_PROJECT_OWNER','Title for return to Project Owner','Content for return to Project Owner','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RET_HR_OFFICER','Title for return to HR Officer','Content for return to HR Officer','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RET_FIN_ADMIN','Title for return to FIN admin','Content for return to FIN admin','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('RET_FIN_HOSP_IC','Title for return to FIN hospital IC','Content for return to FIN hospital IC','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ECLAIM.XXEC_EMAIL_TEMPLATE (TEMPLATE_ID,TEMPLATE_TITLE,TEMPLATE_CONTENT,REC_STATE,CREATED_BY,CREATED_ROLE_ID,CREATED_DATE,UPDATED_BY,UPDATED_ROLE_ID,UPDATED_DATE) values ('PROJECT_APPROVED','Title for project approved','Content for project approved','A','SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'SYSTEM','SYSTEM',to_timestamp('14-NOV-18 05.30.59.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
